baseURL = "https://tobiasehlert.github.io/"
title = "tobiasehlert.github.io"

theme = "hugo-coder"
publishdir = "_site"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableGitInfo = true
enableRobotsTXT = true

disableKinds = ["taxonomy"]

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
